### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by gocci45** [gocci45/furima-32064#9]
フリマアプリのURL
https://furima-32064.herokuapp.com/

Basic認証のIDとパスワード
ID：gocci
パスワード：2222

出品者用のメールアドレスとパスワード
testdesu@test.ne.jp
test1111

購入者用のメールアドレスとパスワード
yuto.yogotti35@icloud.com
yogo0305

購入用カードの番号・期限・セキュリティコード
4242424242424242
期日は3月/22年でローカルホストで成功しています
123

**Comment by tomoko-yokoyama** [comment]
与語さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
